# Generated by Django 5.0.7 on 2025-05-29 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('working_days', models.CharField(help_text='Comma‑separated values among Mon,Tue,Wed,Thu,Fri,Sat,Sun', max_length=50)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=50)),
                ('start_date', models.DateField()),
                ('required_hours', models.PositiveIntegerField(help_text='Number of required hours per working day')),
                ('shift_type', models.CharField(choices=[('standard', 'Standard'), ('adjustable', 'Adjustable')], default='standard', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('repeat_option', models.CharField(choices=[('none', 'None'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly')], default='none', max_length=20)),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='shifts', to='projects.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
