# Generated by Django 5.2.3 on 2025-07-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='required_hours',
            field=models.PositiveIntegerField(help_text='Required hours per working day'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='working_days',
            field=models.CharField(help_text='Comma-separated days (e.g. Mon,Tue,Wed)', max_length=50),
        ),
    ]
