# Generated by Django 5.0.7 on 2025-05-26 19:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('apply_to_new', models.BooleanField(default=False, help_text='If True, automatically apply this policy to any newly created members.')),
                ('max_minutes_per_day', models.PositiveIntegerField(default=0, help_text='Maximum minutes allowed per day (e.g. 30).')),
                ('type', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('created_at', models.DateTimeField(null=True)),
                ('members', models.ManyToManyField(blank=True, help_text='Which members this break policy applies to.', related_name='break_policies', to='projects.member')),
            ],
        ),
        migrations.CreateModel(
            name='BreakSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('accumulated', models.BigIntegerField(default=0)),
                ('is_running', models.BooleanField(default=True)),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_break', to='projects.member')),
                ('policy', models.ForeignKey(blank=True, help_text='Which BreakPolicy this session is following.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtimemonitoring.breakpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('accumulated', models.BigIntegerField(default=0)),
                ('is_running', models.BooleanField(default=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_session', to='projects.member')),
            ],
        ),
    ]
