# Generated by Django 5.2.3 on 2025-07-03 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_created_by'),
        ('realtimemonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='projects.project'),
        ),
    ]
