import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header";
import Sidebar from "@/components/Layout/Sidebar";
import "bootstrap/dist/css/bootstrap.min.css"; // Bootstrap CSS
import BootstrapClient from "@/components/BootstrapClient"; // Import the client component


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WEBWIZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
         <BootstrapClient />
        {/* Header Component */}
        

        {/* Main Layout with Sidebar and Children */}
          {/* Main Content Area */}
          <main id="main"  className="flex-1">
            <div className="container-fluid px-0">
              <div className="row">
                <div className="col-lg-2 px-lg-0 sidebar-col">
                  <Sidebar />
                </div>
                <div className="col-lg-10 px-lg-0 content-col">
                  
                  <Header />
                  <div className="content-main px-3">
                  {children}
                  </div>
                </div>
              </div>
            </div>
           
          </main>
     
      </body>
    </html>
  );
}